last_joint_mount:
  yam:
    v1:
      pos: "0.0404996 0 -0.0356"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
  yam_pro:
    v1:
      pos: "0.0404996 0 -0.0356"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
  yam_ultra:
    v1:
      pos: "0.0404996 0 -0.0419481"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
    v2:
      pos: "0.0404996 0 -0.0419481"
      quat: "0 0.70711 0.70711 0"
      axis: "0 0 1"
  big_yam:
    v1:
      pos: "0.0356 0 -0.0404996"
      quat: "0.5 -0.5 0.5 -0.5"
      axis: "0 0 1"

# No gripper motor
motor_type: ""
motor_kp: -1.0
motor_kd: -1.0

gripper_limits: null
needs_calibration: false

limiter: null
